spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/app10_prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldjlocal
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    com.ll.exam.app10: info
custom:
  genFileDirPath: /gen