spring:
  datasource:
    url: jdbc:mariadb://${testDbIp:127.0.0.1}:3306/app10_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${testDbId:root}
    password: ${testDbPw:1234}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create